#!/bin/bash

# Copyright 2025 The wgsl-fuzz Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir sampleShaderHtml
mkdir referenceImages

./scripts/standAloneShaderHtml --shaderFolderPath samples --output sampleShaderHtml

pushd src/main/checkSemanticsPreserving
  npm install
popd

node ./scripts/renderShaderHtml/cli.js --chrome "$(which chromium-browser)" --chromeArgs "--enable-unsafe-webgpu" --jobDir "sampleShaderHtml" --outputDir "referenceImages"
